package telemetry

//go:generate go run ./gen -o ../../docs/telemetry.md

import (
	"fmt"
	"sort"
	"strings"
)

// Markdown renders the catalogue as `docs/telemetry.md`. Generated rather than
// written by hand for the reason the whole catalogue exists: a hand-written
// list of what an analytics client sends is a list that is wrong within a
// month. `go generate ./internal/telemetry` rewrites the file and
// TestDocsAreCurrent fails if it is stale, so the published page and the code
// cannot disagree.
//
// The audience is someone deciding whether to switch this on. That means
// leading with what is *not* sent, being specific about the one place where
// free text could appear and what happens to it, and being honest about the
// data PostHog collects on its own account rather than only the data we choose
// to send.
func Markdown() string {
	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
		b.WriteString("\n")
	}

	w("<!-- Generated by `go generate ./internal/telemetry` from internal/telemetry/catalogue_events.go.")
	w("     Do not edit by hand: the generator overwrites this file and a test fails when it is stale. -->")
	w("")
	w("# Telemetry")
	w("")
	w("matterbox can report anonymous usage data to help work out which parts of it")
	w("are useful, which are ignored, and which are quietly broken. It is **off unless")
	w("you turned it on**, and this page is the complete list of what it sends.")
	w("")
	w("```yaml")
	w("# ~/.config/matterbox/config.yaml")
	w("telemetry:")
	w("  enabled: false          # nothing is sent unless this is explicitly true")
	w("  anonymous_id: \"\"        # random id events are grouped by; delete it for a fresh one")
	w("```")
	w("")
	w("Setting `enabled: false` stops it for good, and so does removing the")
	w("`telemetry` section entirely. Deleting `anonymous_id` makes your future events")
	w("unlinkable to your past ones.")
	w("")
	w("That config key is the **only** gate. The PostHog project key is compiled into")
	w("the binary, release builds included — but it does nothing on its own: with the")
	w("key present and consent absent, nothing is sent.")
	w("")
	w("*Where* events go is a separate question from *whether* they are sent, and it")
	w("has two knobs. Neither grants consent:")
	w("")
	w("| Knob | When | What it does |")
	w("|---|---|---|")
	w("| `make POSTHOG_KEY=phc_…` | build time | Compiles a different project key in. Pass it empty — `make POSTHOG_KEY=` — to build a binary with no key at all, which can report nowhere. |")
	w("| `%s` | run time | Overrides the compiled-in key for one run, for pointing a build at your own project. |", KeyEnv)
	w("| `%s` | run time | Overrides the ingest host (default `%s`). |", HostEnv, endpoint)
	w("")
	w("To see where all of that landed on your own machine, ask the binary:")
	w("`matterbox --version` prints a `telemetry:` line reporting whether it would")
	w("send anything — and if not, whether that is because nobody has answered the")
	w("question, because the answer was no, or because the build carries no key.")
	w("")

	w("## The update check, which is not this")
	w("")
	w("One other thing matterbox does over the network on its own, and it is worth")
	w("naming here because this is the page people read to find out. Once a day it")
	w("fetches <https://matterbox.work/latest.json> to see whether a newer release")
	w("exists. That is not telemetry and is not behind this consent: the request")
	w("carries no version, no platform and no identifier, the file answers everyone")
	w("the same way, and the comparison happens on your machine — so there is nothing")
	w("in it to count installs with, and it reveals no more than opening the website")
	w("does. It is on by default, and `update_check.enabled: false` turns it off. See")
	w("[config.md](config.md).")
	w("")
	w("The two do meet in one place. Whether people upgrade at all is a real")
	w("question, and `version_upgraded` below is what answers it — with consent,")
	w("like everything else on this page.")
	w("")

	w("## The setup wizard, which asks before it can send")
	w("")
	w("The wizard asks the telemetry question on its last screen, so everything")
	w("before it happens with the answer unknown. Its own funnel — which step you")
	w("reached, how many times a step was shown, whether a sign-in was rejected — is")
	w("therefore held in memory and **only sent if you answer yes**. Answer no, or")
	w("quit before the question, and the buffer is discarded: it never reaches the")
	w("network, and nothing on disk records that it existed.")
	w("")
	w("The same holds for the subcommands. Telemetry is started once a verb has")
	w("finished — so `matterbox decode` never reads a config it has no use for —")
	w("which means anything the verb wanted to report is held until then and")
	w("discarded if consent is absent.")
	w("")
	w("## What is never sent")
	w("")
	w("None of the following has any representation in the event catalogue below —")
	w("not as a property, not in an id, not in an error message:")
	w("")
	w("- **Message text.** No message body, draft, edit or search query. Where the")
	w("  size of something matters it is bucketed (`501-2000` characters), never quoted.")
	w("- **Names.** No username, display name, nickname or email — yours or anyone")
	w("  else's. Mentions are counted, never named.")
	w("- **Channels and teams.** No channel or team name, id, purpose or member list.")
	w("  The *kind* of conversation (public, private, DM, group DM) is sent, because")
	w("  \"people live in DMs\" changes what the sidebar should do — and it names nobody.")
	w("- **Your server.** No Mattermost URL, hostname or instance name, so events")
	w("  cannot be tied to an employer.")
	w("- **Files and paths from your machine.** No filename you opened, no")
	w("  directory, no home directory. File *kind* and bucketed size only. The one")
	w("  kind of path that is sent is a source path from matterbox's own public")
	w("  repository — `internal/ui/view.go:1602`, in a crash report — which is a")
	w("  line of code, not a thing on your disk. See the error-report section.")
	w("- **Credentials.** No token, password or session id.")
	w("- **Keystrokes as text.** No single-character keystroke is ever reported. The")
	w("  one event about keys (`unhandled_key`) draws from a fixed list containing")
	w("  only multi-character keystrokes — `ctrl+w`, `f5`, `pgup`, `alt+enter` — and")
	w("  fires only when no text input has focus. An unhandled bare letter is reported")
	w("  as `other`: that a key did nothing, and where, but not which one. A stream of")
	w("  these cannot spell anything.")
	w("")

	w("## Where free text could appear, and what happens to it")
	w("")
	w("Two things carry prose, and both are the same thing: scrubbed error text, on")
	w("the `operation_failed` and `panic_recovered` events and on the error reports")
	w("below. Error strings are where private data")
	w("leaks in practice — `open /home/ana/.config/matterbox/messages.db: permission")
	w("denied` is a username, and `post \"shall we ship it?\" rejected` is a message —")
	w("so every such value is put through a scrubber first, which replaces:")
	w("")
	w("| Pattern | Becomes |")
	w("|---|---|")
	w("| URLs, including `ws://` | `<url>` |")
	w("| Email addresses | `<email>` |")
	w("| Absolute, `~`-relative and Windows paths | `<path>` |")
	w("| 26-character Mattermost ids (post, channel, user, team, file) | `<id>` |")
	w("| `@mentions` | `<mention>` |")
	w("| Anything in single, double or back quotes | `<quoted>` |")
	w("| Runs of 7+ digits | `<num>` |")
	w("| Alphanumeric runs of 32+ characters | `<token>` |")
	w("")
	w("What survives is the part that says what went wrong (`permission denied`),")
	w("capped at 200 characters. If nothing but placeholders is left, the value is")
	w("replaced with `<redacted>` — the event still records that something failed.")
	w("")
	w("Stack frames on `panic_recovered` are filtered to functions inside the")
	w("matterbox module — `internal/ui.(*Model).renderMessages` — with no arguments,")
	w("no file paths, and no frames from the standard library or dependencies.")
	w("")

	// -- error reports -----------------------------------------------------
	w("## Error reports")
	w("")
	w("Crashes and failures are also sent to PostHog's error-tracking view, as")
	w("`$exception` records rather than as events. They are the same consent and the")
	w("same anonymous id — telemetry off means none of this happens — and they exist")
	w("because an event can say *that* something broke while only a stack can say")
	w("*where*.")
	w("")
	w("Not every failure becomes one. A panic always does. A failed operation does")
	w("only when its class says the fault is ours — a parse error, a bad config, an")
	w("internal error — and never when the class says it was the world: `network`,")
	w("`server`, `rate_limited`, `auth`, `permission`, `not_found`. Those are counted")
	w("by `operation_failed` and go no further, because a dropped connection is a")
	w("number rather than a bug, and thousands of them would bury the real ones.")
	w("")
	w("A report carries:")
	w("")
	w("| Part | What it holds |")
	w("|---|---|")
	w("| Title | The failure site (`store.migrate`) or `panic in <function>`. Both from the fixed lists on this page. |")
	w("| Description | Scrubbed error or panic text, exactly as described above. |")
	w("| `where`, `class` | The same closed sets the events use, validated the same way. |")
	w("| `handled` | Whether matterbox carried on afterwards. |")
	w("| `os`, `arch`, `version`, `build_tags` | The machine and the build, as on `app_started`. |")
	w("| Stack | matterbox frames only: `internal/ui/view.go:1602 internal/ui.(*Model).View`. |")
	w("")
	w("The stack is the part worth being precise about, because it is the part that")
	w("could leak. The PostHog SDK builds one for you, and matterbox does not use it:")
	w("the SDK records each frame's file path as the compiler saw it, which on a")
	w("matterbox built from source is an absolute path through your home directory,")
	w("and it attaches raw instruction addresses and an")
	w("identifier for your executable besides.")
	w("")
	w("So frames are rebuilt from scratch, and the rule is the opposite one: a frame")
	w("is dropped unless it can be *proved* to belong to matterbox, by reducing its")
	w("recorded path against this build's own module root. A frame from the standard")
	w("library, a dependency or a vendored tree does not reduce, so it is dropped")
	w("rather than filtered — anything unrecognised fails closed. What survives is a")
	w("file and line of a public repository. Nothing identifies the machine, and")
	w("because no executable identifier is sent, PostHog's source-context feature")
	w("stays dark: that is the trade, and it is deliberate.")
	w("")
	w("One session may send at most %d reports, and at most %d of any one issue, so a",
		maxExceptionsPerSession, maxExceptionsPerIssue)
	w("failure inside a retry loop cannot flood.")
	w("")

	w("## What PostHog collects on its own account")
	w("")
	w("Being complete means naming the data we do not choose to send.")
	w("")
	w("Events are delivered to PostHog Cloud EU over HTTPS, so PostHog's servers")
	w("see the connecting IP address in transit, as any service you talk to does.")
	w("It goes no further: the project is configured to discard client IPs, so the")
	w("address is never stored with an event — transformations such as bot")
	w("detection may use it, then it is thrown away. Your IP is not something")
	w("matterbox puts in an event either. Location lookup is off regardless:")
	w("every event carries `$geoip_disable`, which is the Go SDK's default and")
	w("is not overridden here, so no country, region or city is derived from")
	w("that address. PostHog does stamp each event with a receive time.")
	w("")
	w("The SDK also stamps four properties of its own on every event, before")
	w("matterbox sees the payload and with no setting to turn them off:")
	w("")
	w("| Property | Example | Note |")
	w("|---|---|---|")
	w("| `$os` | `Linux` | Duplicates the catalogue's `os`. |")
	w("| `$os_version` | `44` | The distribution's release, which the catalogue does not ask for. |")
	w("| `$os_distro` | `Fedora Linux Asahi Remix` | The distribution's name, which the catalogue does not ask for. |")
	w("| `$go_version` | `go1.26.6-X:nodwarf5` | The **untrimmed** toolchain string. |")
	w("")
	w("The last one is worth calling out, because it partly undoes a decision made")
	w("here: the catalogue's own `go_version` is trimmed to `go1.26.6` precisely")
	w("because the full string can carry local toolchain flags that describe someone's")
	w("build environment. The SDK sends the untrimmed one alongside it. This page")
	w("would rather say so than claim a completeness it does not have.")
	w("")

	w("## How the guarantees above are enforced")
	w("")
	w("Not by convention. Every event and property is declared in")
	w("`internal/telemetry/catalogue_events.go`, and the sending path checks each")
	w("value against its declaration before queuing it:")
	w("")
	w("- An **event name** not in the catalogue is dropped.")
	w("- A **property** not declared on that event is dropped.")
	w("- An **enum** value outside its declared set is dropped — and almost every")
	w("  property is an enum, including every bucketed number, so the full set of")
	w("  values a property can ever hold is finite and listed on this page.")
	w("- **Counter map** keys outside their whitelist are dropped.")
	w("")
	w("So a call site that accidentally passed a message body would not leak it: the")
	w("value would fail validation and never be sent. In tests the same violations")
	w("panic instead, so a mistake fails CI rather than shipping. This page is")
	w("generated from those declarations, which is why it can claim to be complete.")
	w("")
	w("Error reports do not go through the catalogue — they are not events — so they")
	w("get the same treatment by a different route: every label on one is checked")
	w("against the same closed sets, the message goes through the same scrubber, and")
	w("every stack frame has to prove it is matterbox's own code. The section above")
	w("describes what that leaves. The properties the SDK adds by itself are outside")
	w("both mechanisms, and are named in full below.")
	w("")

	// -- events ------------------------------------------------------------
	live, planned := 0, 0
	for _, e := range Events {
		if e.Planned {
			planned++
		} else {
			live++
		}
	}
	w("## Events")
	w("")
	w("%d events, %d of them sent by the current build.", len(Events), live)
	if planned > 0 {
		w("")
		w("%d are declared but not yet emitted anywhere; they are listed so this page", planned)
		w("describes the whole design rather than a moving subset of it, and are marked")
		w("**not yet sent**.")
	}
	w("")
	w("Two events carry most of the volume. `usage_snapshot` is a periodic tally of")
	w("everything too frequent to send individually — keystrokes, clicks, commands —")
	w("flushed every 5 minutes and once at exit. Everything else is sent as it")
	w("happens, because for those the ordering is part of the answer.")
	w("")
	for i := range Events {
		e := &Events[i]
		w("### `%s`", e.Name)
		w("")
		tags := []string{}
		if e.Planned {
			tags = append(tags, "**not yet sent**")
		}
		if e.Daemon {
			tags = append(tags, "sent only by the `matterbox listen` daemon")
		}
		if len(tags) > 0 {
			w("%s", strings.Join(tags, " · "))
			w("")
		}
		w("%s", wrapText(e.Desc, 78))
		w("")
		w("**Why:** %s", wrapText(e.Why, 78))
		w("")
		if len(e.Props) == 0 {
			w("No properties.")
			w("")
			continue
		}
		w("| Property | Type | Meaning |")
		w("|---|---|---|")
		for _, p := range e.Props {
			w("| `%s` | %s | %s |", p.Name, p.Kind.String(), cell(p.Desc)+valueHint(p))
		}
		w("")
	}

	// -- value sets --------------------------------------------------------
	w("## Value sets")
	w("")
	w("The closed sets the properties above draw from. A property can hold nothing")
	w("outside its set — that is checked at runtime, not just documented.")
	w("")
	for _, s := range valueSets() {
		w("### %s", s.name)
		w("")
		if s.note != "" {
			w("%s", wrapText(s.note, 78))
			w("")
		}
		w("%s", codeList(s.values))
		w("")
	}

	w("## Checking for yourself")
	w("")
	w("Don't take this page's word for it. Point a build at a PostHog project you own,")
	w("using the run-time knobs from the table above, and read exactly what arrives:")
	w("")
	w("```sh")
	w("export %s=phc_your_own_key", KeyEnv)
	w("export %s=%s", HostEnv, endpoint)
	w("make run")
	w("```")
	w("")
	w("Consent still applies — `telemetry.enabled` must be true. Grepping the source")
	w("for `telemetry.` shows every call site; each one resolves to a typed emitter")
	w("in `internal/telemetry/emit.go`, and every emitter maps to an event on this")
	w("page.")

	return b.String()
}

// valueSet is one closed set for the documentation.
type valueSet struct {
	name   string
	note   string
	values []string
}

// valueSets returns the shared sets worth documenting on their own, rather than
// repeating inline in every property row that uses them.
func valueSets() []valueSet {
	return []valueSet{
		{"Count buckets", "Used wherever a number describes user content — posts, results, mentions, replies.", CountBuckets},
		{"Length buckets", "Characters of text. Used for message and query length; the text itself is never sent.", LengthBuckets},
		{"Duration buckets (ms)", "Latencies and frame times.", MillisBuckets},
		{"Duration buckets (s)", "Human-scale spans: session length, how long a picker stayed open, message age.", SecondsBuckets},
		{"Terminal width buckets", "The layout's own breakpoints, not round numbers.", ColsBuckets},
		{"Terminal height buckets", "", RowsBuckets},
		{"File size buckets", "", BytesBuckets},
		{"Result rank buckets", "Position of an opened search hit, so \"is the top result right\" is answerable.", RankBuckets},
		{"Contexts", "The layers of the key-handling ladder — the panes, modes and modals that can own a keystroke. Taken from the keyContexts table in internal/ui/contexts.go, which is the app's own tested model of which bindings are live where.", Contexts},
		{"Channel types", "The kind of conversation. Never its name or id.", ChannelTypes},
		{"Open routes", "How a conversation was reached.", OpenVias},
		{"Outcomes", "", Outcomes},
		{"Error classes", "Grouped by what a user would have to do about them.", ErrorClasses},
		{"Image protocols", "Terminal graphics support.", ImageProtocols},
		{"Reportable keys", "The only keystrokes unhandled_key may report: non-text keys, so a stream of them cannot reconstruct anything typed.", ReportableKeys},
		{"Action ids", "Every rebindable action in the keymap. The usage snapshot counts each one, which is how a binding nobody uses becomes visible.", ActionIDs},
		{"Mouse targets", "The clickable regions of the UI.", MouseTargets},
		{"Command palette ids", "The \">\" palette entries, by stable id — several display names interpolate a channel name, which is never sent.", PaletteIDs},
		{"Slash commands", "Built-in \"/\" commands. Server and plugin commands count as `server` without their trigger word, since those names are organisation-specific.", SlashIDs},
		{"Feature ids", "The features whose adoption is counted.", FeatureIDs},
		{"Friction signals", "The counted signs that something was not understood. See the `friction` event for what each means.", FrictionIDs},
		{"Failure sites", "Hand-written labels naming where something failed. Constants in the source, never derived from data.", FailureSites},
		{"CLI commands", "", CLICommands},
	}
}

// valueHint appends the allowed values to a property's description, for the
// small sets that read better inline than as a cross-reference.
func valueHint(p PropSpec) string {
	if len(p.Values) == 0 || len(p.Values) > 8 {
		return ""
	}
	// Skip the shared sets — they have their own section, and repeating a
	// bucket list on twenty rows makes the tables unreadable.
	for _, s := range valueSets() {
		if sameSet(s.values, p.Values) {
			return ""
		}
	}
	quoted := make([]string, len(p.Values))
	for i, v := range p.Values {
		quoted[i] = "`" + v + "`"
	}
	return " One of " + strings.Join(quoted, ", ") + "."
}

func sameSet(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// codeList renders a value set as a wrapped run of code spans.
func codeList(values []string) string {
	sorted := append([]string(nil), values...)
	sort.Strings(sorted)
	var b strings.Builder
	line := 0
	for i, v := range sorted {
		item := "`" + v + "`"
		if i > 0 {
			if line+len(item)+2 > 78 {
				b.WriteString(",\n")
				line = 0
			} else {
				b.WriteString(", ")
				line += 2
			}
		}
		b.WriteString(item)
		line += len(item)
	}
	return b.String()
}

// cell makes a description safe for a markdown table cell.
func cell(s string) string {
	return strings.ReplaceAll(strings.Join(strings.Fields(s), " "), "|", "\\|")
}

// wrapText hard-wraps prose so the generated file reads like the rest of the
// docs directory rather than one long line per paragraph.
func wrapText(s string, width int) string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return ""
	}
	var b strings.Builder
	line := 0
	for i, word := range words {
		if i > 0 {
			if line+1+len(word) > width {
				b.WriteString("\n")
				line = 0
			} else {
				b.WriteString(" ")
				line++
			}
		}
		b.WriteString(word)
		line += len(word)
	}
	return b.String()
}
