package ui

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"image"
	"image/draw"
	_ "image/gif"  // GIF attachments (decoded via decodeImageFrames)
	_ "image/jpeg" // JPEG attachments
	_ "image/png"  // PNG attachments
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"charm.land/bubbles/v2/key"
	tea "charm.land/bubbletea/v2"
	"charm.land/lipgloss/v2"
	"github.com/mattermost/mattermost/server/public/model"
	xdraw "golang.org/x/image/draw"
)

// previewHTTPClient fetches external preview images (e.g. GIF-picker ![](…)
// links). The timeout bounds a slow or hung host; the modal surfaces the error
// if it trips.
var previewHTTPClient = &http.Client{Timeout: 30 * time.Second}

// previewMaxImageBytes caps an external image download so a pathological URL
// can't exhaust memory; generous for a GIF.
const previewMaxImageBytes = 32 << 20 // 32 MiB

// The image-preview modal: press space on a message carrying an image — either
// an uploaded attachment or an image URL in the body (e.g. a GIF-picker
// ![](…) link) — to view it inline, rendered via the Kitty Unicode-placeholder
// protocol (the same mechanism custom emoji use — see emojiimg.go — so it
// survives the TUI's per-frame repaints). Closable with space/esc/q; ←/→ cycle
// when a post has several images.
//
// Kitty-only by design: there is no ASCII/half-block fallback, so the modal is
// available only when the custom-emoji graphics probe came back OK on a
// truecolor terminal (m.emojiImg.active()). Animated GIFs cycle through their
// frames (same single-id re-transmit technique custom emoji use) unless the
// animations.image_preview config toggle is off, in which case they show the
// first frame only. See IMAGE_PREVIEW_ANIMATION.md.

// previewItem is one previewable image on a post: either an uploaded attachment
// (downloaded through the Mattermost client) or an external image URL from the
// message body (e.g. a GIF-picker ![](…) link), fetched over HTTP. Exactly one
// of file / url is set.
type previewItem struct {
	file *model.FileInfo
	url  string
	name string
}

// previewState holds the live image-preview modal. The zero value is closed.
type previewState struct {
	active bool

	// items is the post's previewable images (attachments first, then body image
	// URLs); idx is the one on screen. ←/→ move idx when len(items) > 1.
	items []previewItem
	idx   int

	// loading is true while the current file downloads/decodes; err records a
	// failure. Mutually exclusive with a non-nil img.
	loading bool
	err     error

	// img is the first decoded frame (used for sizing + the caption); caption is
	// the line shown beneath the image.
	img     image.Image
	caption string

	// frames/delays hold the decoded image: a still image is a single frame with
	// a nil delays slice; an animated GIF (when animations.image_preview is on)
	// has every composited frame and its per-frame display time. frameIdx is the
	// frame currently transmitted under id; frameStart is when it began showing.
	// All frames share one image id, so animating is a re-transmit, not a
	// re-render (mirrors the custom-emoji loop in emojiimg.go).
	frames     []image.Image
	delays     []time.Duration
	frameIdx   int
	frameStart time.Time

	// seqs is the Kitty transmit sequence for each frame, pre-built off the main
	// thread (download/decode/encode all happen in the background command) and
	// parallel to frames. The Update loop and the animation tick only write the
	// ready bytes — they never PNG-encode, so a multi-megapixel photo can't block
	// the UI. Regenerated by reencodePreview on resize.
	//
	// With native set, seqs always has exactly one entry: the Kitty
	// native-animation *root* transmit alone (see encodePreviewNative), not a
	// per-frame sequence — the follow-up (every other frame + the
	// terminal-driven loop) is folded onto it separately, once
	// previewNativeSetupMsg arrives. frames/delays are still the full decode
	// (reencodePreview needs them to rebuild both at a new size), but nothing
	// here reads seqs frame-by-frame.
	seqs []string

	// native records whether this preview's animation (if any) is running via the
	// Kitty native-animation frames (animations.native_animation) rather than the
	// per-frame re-transmit tick below. Sticky for the life of one loaded image —
	// cyclePreview/loadPreviewImage decide it afresh for whatever comes next.
	native bool

	// rows/cols is the placement size in text cells, recomputed on load and on
	// resize from the image aspect and the terminal size.
	rows, cols int

	// id is the Kitty image id the current frame was transmitted under,
	// allocated from emojiImg.allocID() and freed with kittyDelete on close. A
	// native resize allocates a fresh id (see reencodePreview) rather than
	// reusing this one, to avoid re-transmitting a root frame under an id that
	// already carries animation frames at the old size — an interaction the
	// protocol doesn't spell out.
	id uint32

	// --- streaming video playback (space on a video attachment) ---------------
	// When streaming is set, this preview is a video played incrementally rather
	// than decoded whole: stream is the live decoder, and instead of the fixed
	// frames/seqs slices above, frames flow through streamBuf. A decode-ahead Cmd
	// keeps streamBuf topped up while the tick plays and evicts from its front, so
	// a long clip starts fast and never holds more than streamBufferFrames at once.
	// Plays once and stops on the last frame (streamDone). See the streaming
	// player below and video.go. Nil/false for images and GIFs.
	streaming bool
	stream    videoStream
	// streamBuf is the FIFO of decoded, pre-encoded frames waiting to be shown;
	// the tick pops the front. streamEOF means the decoder is exhausted (streamBuf
	// is then all that's left); streamFetching means a decode-ahead Cmd is in
	// flight (so we don't launch a second); streamDone means playback reached the
	// end and the last frame is held.
	streamBuf      []streamFrame
	streamEOF      bool
	streamFetching bool
	streamDone     bool
}

// previewImageLoadedMsg carries a finished background decode. gen guards against
// a stale result the user already cycled/closed past (see Model.previewGen).
// frames has one entry for a still image and many for an animated GIF; delays is
// parallel to frames (nil for a still image).
type previewImageLoadedMsg struct {
	gen    int
	frames []image.Image
	delays []time.Duration
	seqs   []string // pre-built Kitty transmit sequence per frame (parallel to frames)
	native bool     // seqs[0] is a native-animation *root* alone, not one seq per frame
	// nativeSetup is the native-animation follow-up (every remaining frame + the
	// terminal-driven loop) for a native, multi-frame result — set only when
	// native is true. It is deliberately not part of seqs: handlePreviewLoaded
	// transmits seqs[0] (the root) immediately, and this is delivered as its own
	// message at least one event later (see previewNativeSetupMsg), so the root
	// gets a chance to actually resolve before the larger follow-up competes for
	// the terminal's attention — the same race described on
	// readyEmoji.nativeSetup.
	nativeSetup string
	cols        int
	rows        int
	caption     string
	err         error
}

// previewReencodedMsg carries frames re-encoded at a new placement size (after a
// terminal resize). gen drops a result the user has since cycled/closed past. id is
// set (nonzero) only for a native-animation reencode, which allocates a fresh image
// id rather than reusing the old one (see reencodePreview) — oldID is then what to
// kittyDelete.
type previewReencodedMsg struct {
	gen       int
	seqs      []string
	id, oldID uint32
	// nativeSetup is the native-animation follow-up for a native reencode (id !=
	// 0) — sent separately, one event later, for the same reason
	// previewImageLoadedMsg.nativeSetup is: so the fresh root has a chance to
	// resolve before it.
	nativeSetup string
	err         error
}

// previewTickMsg drives the preview modal's GIF animation. gen drops a tick from
// a preview the user has since cycled or closed (see Model.previewGen).
type previewTickMsg struct{ gen int }

// previewAnimMinInterval floors the preview animation cadence, capping the
// wakeup rate for a GIF that claims very short per-frame delays.
const previewAnimMinInterval = 50 * time.Millisecond

// previewableMIME reports whether we can decode and preview a file inline. We
// render Kitty-only and decode with the stdlib image package (+gif/jpeg/png),
// so those qualify; anything else (webp, svg, tiff, …) is left to `o`.
func previewableMIME(mime string) bool {
	switch mime {
	case "image/png", "image/jpeg", "image/jpg", "image/gif":
		return true
	}
	return false
}

// previewImages enumerates a post's previewable images: uploaded attachments
// (previewable MIME, metadata order) followed by image URLs in the body — the
// ![](…) links a GIF picker posts, plus any bare/linked URL whose path looks
// like an image. Reuses collectOpenables so the extraction + dedup matches what
// `o` opens. URLs are previewable only if their extension is one stdlib decodes.
//
// allowVideo also admits short-clip video attachments (mp4/webm/…), which only
// this session's Model can decide (needs the video build + native_animation on);
// callers pass m.videoPlayable(). It is a plain bool, not derived here, so
// previewImages stays a pure function the tests can drive without a Model.
func previewImages(p *model.Post, allowVideo bool) []previewItem {
	if p == nil {
		return nil
	}
	var out []previewItem
	for _, o := range collectOpenables(p) {
		switch {
		case o.file != nil:
			if previewableMIME(o.file.MimeType) || (allowVideo && isVideoAttachment(o.file)) {
				out = append(out, previewItem{file: o.file, name: o.file.Name})
			}
		case isPreviewableImageURL(o.url):
			out = append(out, previewItem{url: o.url, name: o.name})
		}
	}
	return out
}

// isPreviewableImageURL reports whether a URL's path ends in an extension we can
// decode and render (Kitty-only, stdlib decoders). The query string — which a
// CDN like Giphy stuffs with cache keys — is ignored.
func isPreviewableImageURL(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil {
		return false
	}
	switch strings.ToLower(path.Ext(u.Path)) {
	case ".png", ".jpg", ".jpeg", ".gif":
		return true
	}
	return false
}

// openImagePreview raises the preview modal for the first previewable image on
// p (←/→ cycle the rest). No image → a status hint; no terminal graphics → a
// hint to use `o`, since we render Kitty-only.
func (m Model) openImagePreview(p *model.Post) (tea.Model, tea.Cmd) {
	items := previewImages(p, m.videoPlayable())
	if len(items) == 0 {
		m.status = "no image to preview on this message"
		return m, nil
	}
	return m.openPreviewItems(items, 0)
}

// openPreviewItems raises the preview modal on items[start], with ←/→ cycling
// the rest. Callers own the gallery: a post's own images (openImagePreview) or
// every previewable file in the channel (the info panel's media view). start is
// clamped, so a caller that lost track of its index still opens something.
func (m Model) openPreviewItems(items []previewItem, start int) (tea.Model, tea.Cmd) {
	if len(items) == 0 {
		m.status = "no image to preview"
		return m, nil
	}
	if start < 0 || start >= len(items) {
		start = 0
	}
	if m.emojiImg == nil || !m.emojiImg.active() {
		m.status = "image preview unavailable: " + m.emojiImg.statusReason() + " — press o to open"
		return m, nil
	}
	id := m.emojiImg.allocID()
	m.preview = previewState{active: true, items: items, idx: start, loading: true, id: id}
	m.previewGen++
	return m, m.loadPreviewItem(m.previewGen, id, items[start])
}

// loadPreviewImage fetches (reusing the on-disk cache), decodes, sizes, and
// encodes the image entirely in the background, returning a
// previewImageLoadedMsg tagged with gen. id is the (already-allocated) Kitty
// image id the sequences are built for. Encoding here — not in the Update
// handler — is what keeps a slow PNG encode off the UI goroutine.
func (m Model) loadPreviewImage(gen int, id uint32, it previewItem) tea.Cmd {
	return func() tea.Msg {
		data, err := m.readPreviewBytes(it)
		if err != nil {
			return previewImageLoadedMsg{gen: gen, err: err}
		}
		frames, delays, derr := m.decodePreviewFrames(data, m.animatePreview)
		if derr != nil {
			return previewImageLoadedMsg{gen: gen, err: fmt.Errorf("decode image: %w", derr)}
		}
		cols, rows := m.computePreviewCells(frames[0].Bounds())
		native := m.nativeAnim && len(frames) > 1
		var seqs []string
		var nativeSetup string
		var eerr error
		if native {
			var root string
			root, nativeSetup, eerr = m.encodePreviewNative(frames, delays, cols, rows, id)
			seqs = []string{root}
		} else {
			seqs, eerr = encodePreviewFrames(frames, cols, rows, id, m.cellPxW, m.cellPxH)
		}
		if eerr != nil {
			return previewImageLoadedMsg{gen: gen, err: eerr}
		}
		// Report the original's dimensions/size in the caption even when we
		// rendered the smaller preview rendition (frames[0] would be the
		// downscaled bounds), so the caption describes the actual attachment.
		b := frames[0].Bounds()
		w, h, size := b.Dx(), b.Dy(), int64(len(data))
		if it.file != nil {
			if it.file.Width > 0 && it.file.Height > 0 {
				w, h = it.file.Width, it.file.Height
			}
			if it.file.Size > 0 {
				size = it.file.Size
			}
		}
		return previewImageLoadedMsg{
			gen: gen, frames: frames, delays: delays, seqs: seqs, native: native, nativeSetup: nativeSetup,
			cols: cols, rows: rows, caption: previewCaption(it.name, w, h, size),
		}
	}
}

// encodePreviewNative fits every frame to the rows×cols placement and builds the
// Kitty native-animation root transmit and its follow-up (every remaining frame
// plus the terminal-driven loop) *separately* — see previewImageLoadedMsg.nativeSetup
// for why the two must not be sent in the same install. Mirrors encodePreviewFrames'
// per-frame fit (fitFrameToCells) so the two paths place an image identically; only
// how the animation itself is delivered differs.
func (m Model) encodePreviewNative(frames []image.Image, delays []time.Duration, cols, rows int, id uint32) (root, setup string, err error) {
	fitted := make([]image.Image, len(frames))
	for i, f := range frames {
		fitted[i] = fitFrameToCells(f, cols, rows, m.cellPxW, m.cellPxH)
	}
	root, err = kittyTransmitWith(&kittyPNG, id, fitted[0], rows, cols)
	if err != nil {
		return "", "", err
	}
	setup, err = buildNativeAnimSetup(&kittyPNG, id, fitted, delays)
	if err != nil {
		return "", "", err
	}
	return root, setup, nil
}

// readPreviewBytes returns the item's raw bytes: an attachment via the
// Mattermost client (cached by file id), or an external URL over HTTP (cached
// by URL hash).
//
// For a still-image attachment that the server has a preview rendition for, it
// fetches that downscaled rendition (≤~1MP) instead of the original — a phone
// photo's original is many megabytes at 12MP+, and the modal renders into an
// ~800px terminal box, so the original would only be paid for in transfer,
// decode, and PNG re-encode for nothing. The preview is cached under its own
// path so `o` (open externally) and downloads still get the true original.
func (m Model) readPreviewBytes(it previewItem) ([]byte, error) {
	if it.file != nil {
		if m.usePreviewRendition(it.file) {
			if data, err := m.readOrDownloadFilePreview(it.file); err == nil && len(data) > 0 {
				return data, nil
			}
			// Any preview failure (server lacks it, network) falls through to the
			// original so the modal still shows something.
		}
		path, _ := m.cachedFilePath(it.file)
		return m.readOrDownloadFile(path, it.file)
	}
	path, _ := cachedURLPath(it.url)
	return m.readOrDownloadURL(path, it.url)
}

// usePreviewRendition reports whether to fetch the server's downscaled preview
// instead of the original for this attachment. Requires a server-generated
// preview, and never for an animated GIF we intend to animate — its preview is
// a single flattened frame, so the original is needed to play it.
func (m Model) usePreviewRendition(f *model.FileInfo) bool {
	if f == nil || !f.HasPreviewImage {
		return false
	}
	if m.animatePreview && (f.MimeType == "image/gif" || (videoBuild && isVideoAttachment(f))) {
		return false
	}
	return true
}

// readOrDownloadFilePreview returns the file's preview rendition from the
// on-disk cache, falling back to a download (which is then cached). Cached
// separately from the original (a ".preview" sibling) so it never shadows the
// full-resolution bytes the open/download paths read.
func (m Model) readOrDownloadFilePreview(f *model.FileInfo) ([]byte, error) {
	path, _ := m.cachedPreviewPath(f)
	if path != "" {
		if data, err := os.ReadFile(path); err == nil && len(data) > 0 {
			return data, nil
		}
	}
	data, err := m.client.DownloadFilePreview(m.ctx, f.Id)
	if err != nil {
		return nil, err
	}
	if path != "" {
		_ = os.WriteFile(path, data, 0o644) // best effort
	}
	return data, nil
}

// cachedPreviewPath is the on-disk cache path for a file's preview rendition:
// the original's path with a ".preview" suffix, so the two never collide.
func (m Model) cachedPreviewPath(f *model.FileInfo) (string, error) {
	p, err := m.cachedFilePath(f)
	if err != nil {
		return "", err
	}
	return p + ".preview", nil
}

// readOrDownloadFile returns the file's bytes from the on-disk cache, falling
// back to a download (which is then cached). Mirrors openOpenable's caching.
func (m Model) readOrDownloadFile(path string, f *model.FileInfo) ([]byte, error) {
	if path != "" {
		if data, err := os.ReadFile(path); err == nil && len(data) > 0 {
			return data, nil
		}
	}
	data, err := m.client.DownloadFile(m.ctx, f.Id)
	if err != nil {
		return nil, err
	}
	if path != "" {
		_ = os.WriteFile(path, data, 0o644) // best effort
	}
	return data, nil
}

// readOrDownloadURL returns the external image's bytes from the on-disk cache,
// falling back to an HTTP GET (capped at previewMaxImageBytes, then cached).
func (m Model) readOrDownloadURL(path, rawURL string) ([]byte, error) {
	if path != "" {
		if data, err := os.ReadFile(path); err == nil && len(data) > 0 {
			return data, nil
		}
	}
	req, err := http.NewRequestWithContext(m.ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := previewHTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetch image: %s", resp.Status)
	}
	data, err := io.ReadAll(io.LimitReader(resp.Body, previewMaxImageBytes))
	if err != nil {
		return nil, err
	}
	if path != "" {
		_ = os.WriteFile(path, data, 0o644) // best effort
	}
	return data, nil
}

// cachedURLPath returns the on-disk cache path for an external preview image,
// keyed by a hash of the URL (mirrors cachedFilePath/cachedEmojiPath). Holds the
// original downloaded bytes so a warm reopen costs no HTTP.
func cachedURLPath(rawURL string) (string, error) {
	cache, err := os.UserCacheDir()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(cache, "matterbox", "urlimg")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	sum := sha256.Sum256([]byte(rawURL))
	return filepath.Join(dir, hex.EncodeToString(sum[:])), nil
}

// previewCaption builds the line under the image: name · W×H · size (the size is
// omitted when unknown).
func previewCaption(name string, w, h int, size int64) string {
	if size > 0 {
		return fmt.Sprintf("%s · %d×%d · %s", normalizeFilename(name), w, h, humanSize(size))
	}
	return fmt.Sprintf("%s · %d×%d", normalizeFilename(name), w, h)
}

// handlePreviewLoaded installs a finished decode: the placement size and the
// per-frame transmit sequences were already computed in the background, so this
// just stores them and writes the first frame's sequence out of band — no
// encoding on the UI goroutine. A multi-frame GIF (animations on) arms the
// animation tick. Stale results (the user cycled/closed) are dropped.
func (m Model) handlePreviewLoaded(msg previewImageLoadedMsg) (tea.Model, tea.Cmd) {
	if !m.preview.active || msg.gen != m.previewGen {
		return m, nil
	}
	m.preview.loading = false
	if msg.err != nil {
		m.preview.err = msg.err
		return m, nil
	}
	if len(msg.seqs) == 0 || len(msg.frames) == 0 {
		m.preview.err = fmt.Errorf("preview produced no frames")
		return m, nil
	}
	m.preview.frames = msg.frames
	m.preview.delays = msg.delays
	m.preview.seqs = msg.seqs
	m.preview.native = msg.native
	m.preview.cols, m.preview.rows = msg.cols, msg.rows
	m.preview.frameIdx = 0
	m.preview.frameStart = time.Time{}
	m.preview.img = msg.frames[0]
	m.preview.caption = msg.caption
	// A native setup animates itself once sent — see kittyAnimateStart — so only
	// the manual path needs a tick to advance it. The setup itself is sent
	// separately, at least one event later (see previewNativeSetupMsg), so the
	// root above gets a chance to resolve first.
	if msg.native {
		cmds := []tea.Cmd{tea.Raw(msg.seqs[0])}
		if msg.nativeSetup != "" {
			cmds = append(cmds, deliverPreviewNativeSetup(m.previewGen, msg.nativeSetup))
		}
		return m, tea.Batch(cmds...)
	}
	if len(m.preview.frames) > 1 {
		m.preview.frameStart = time.Now()
		return m, tea.Batch(tea.Raw(msg.seqs[0]), previewTickCmd(m.previewGen, m.preview.delays[0]))
	}
	return m, tea.Raw(msg.seqs[0])
}

// previewNativeSetupMsg carries the Kitty native-animation follow-up for the
// preview that is (or was) open — see previewImageLoadedMsg.nativeSetup and
// deliverPreviewNativeSetup.
type previewNativeSetupMsg struct {
	gen   int
	setup string
}

// deliverPreviewNativeSetup hands the setup back as a message on the *next*
// trip through the event loop rather than sending it immediately — see
// emojiimg.go's deliverEmojiNativeSetup for why that gap is what actually
// avoids the terminal's "missing image for virtual placement" warning.
func deliverPreviewNativeSetup(gen int, setup string) tea.Cmd {
	return func() tea.Msg { return previewNativeSetupMsg{gen: gen, setup: setup} }
}

// handlePreviewNativeSetup sends the follow-up for a preview whose root was
// installed and displayed one event ago: fold it onto the entry's one transmit
// sequence and send it. Dropped if the preview has since been cycled or closed
// (gen mismatch) — freePreviewID will have already deleted that id.
func (m Model) handlePreviewNativeSetup(msg previewNativeSetupMsg) (tea.Model, tea.Cmd) {
	if !m.preview.active || msg.gen != m.previewGen || len(m.preview.seqs) == 0 {
		return m, nil
	}
	m.preview.seqs[0] += msg.setup
	return m, tea.Raw(msg.setup)
}

// handlePreviewTick advances the open preview's GIF to the frame due at this
// tick and re-transmits its (pre-built) sequence under the same image id (so the
// on-screen placeholder repaints with no re-render and no encoding), then
// reschedules from the next frame's delay. A tick from a cycled/closed preview,
// or for a still image, is dropped.
func (m Model) handlePreviewTick(msg previewTickMsg) (tea.Model, tea.Cmd) {
	if !m.preview.active || msg.gen != m.previewGen || m.preview.native || len(m.preview.frames) <= 1 ||
		m.preview.id == 0 || len(m.preview.seqs) != len(m.preview.frames) {
		return m, nil
	}
	now := time.Now()
	// Catch up across as many frames as the elapsed time covers, so a late tick
	// doesn't play in slow motion.
	for now.Sub(m.preview.frameStart) >= m.preview.delays[m.preview.frameIdx] {
		m.preview.frameStart = m.preview.frameStart.Add(m.preview.delays[m.preview.frameIdx])
		m.preview.frameIdx = (m.preview.frameIdx + 1) % len(m.preview.frames)
	}
	rem := m.preview.delays[m.preview.frameIdx] - now.Sub(m.preview.frameStart)
	if rem < 0 {
		rem = 0
	}
	return m, tea.Batch(tea.Raw(m.preview.seqs[m.preview.frameIdx]), previewTickCmd(m.previewGen, rem))
}

// handlePreviewReencoded installs frames re-encoded at a new placement size
// (after a resize) and re-transmits the current frame. Stale/failed results are
// dropped; the running animation tick keeps the same gen and picks up the new
// sequences on its next fire.
//
// A native reencode (msg.id != 0) carries a *fresh* image id — see
// reencodePreview — so this also swaps m.preview.id and frees the old one, rather
// than only replacing seqs the way the manual/still path does.
func (m Model) handlePreviewReencoded(msg previewReencodedMsg) (tea.Model, tea.Cmd) {
	if !m.preview.active || msg.gen != m.previewGen || msg.err != nil {
		return m, nil
	}
	if msg.id != 0 {
		m.preview.id = msg.id
		m.preview.seqs = msg.seqs
		m.preview.frameIdx = 0
		cmds := []tea.Cmd{tea.Raw(msg.seqs[0])}
		if msg.oldID != 0 {
			cmds = append(cmds, tea.Raw(kittyDelete(msg.oldID)))
		}
		if msg.nativeSetup != "" {
			cmds = append(cmds, deliverPreviewNativeSetup(m.previewGen, msg.nativeSetup))
		}
		return m, tea.Batch(cmds...)
	}
	if len(msg.seqs) != len(m.preview.frames) {
		return m, nil
	}
	m.preview.seqs = msg.seqs
	if m.preview.frameIdx >= len(msg.seqs) {
		m.preview.frameIdx = 0
	}
	return m, tea.Raw(msg.seqs[m.preview.frameIdx])
}

// previewTickCmd schedules the next preview animation tick after d (floored to
// previewAnimMinInterval), tagged with gen so a stale tick is dropped.
func previewTickCmd(gen int, d time.Duration) tea.Cmd {
	if d < previewAnimMinInterval {
		d = previewAnimMinInterval
	}
	return tea.Tick(d, func(time.Time) tea.Msg { return previewTickMsg{gen: gen} })
}

// cyclePreview moves to the previous/next image on the post, freeing the current
// id and kicking off a fresh load. No-op when the post has a single image.
func (m Model) cyclePreview(delta int) (tea.Model, tea.Cmd) {
	if len(m.preview.items) <= 1 {
		return m, nil
	}
	free := m.freePreviewID()
	m.teardownPreviewStream() // free the old video decoder (unless a Cmd holds it)
	n := len(m.preview.items)
	m.preview.idx = ((m.preview.idx+delta)%n + n) % n
	m.preview.loading = true
	m.preview.err = nil
	m.preview.img = nil
	m.preview.frames = nil
	m.preview.delays = nil
	m.preview.seqs = nil
	m.preview.frameIdx = 0
	m.preview.frameStart = time.Time{}
	m.preview.streaming = false
	m.preview.stream = nil
	m.preview.streamBuf = nil
	m.preview.streamEOF = false
	m.preview.streamFetching = false
	m.preview.streamDone = false
	id := m.emojiImg.allocID()
	m.preview.id = id
	m.previewGen++ // also drops any in-flight animation tick/chunk for the old image
	return m, tea.Batch(free, m.loadPreviewItem(m.previewGen, id, m.preview.items[m.preview.idx]))
}

// closeImagePreview tears down the modal and frees the image id from terminal
// memory. previewGen is bumped so any in-flight load is ignored on arrival.
func (m *Model) closeImagePreview() tea.Cmd {
	cmd := m.freePreviewID()
	m.teardownPreviewStream() // free the video decoder (unless a Cmd holds it — see teardown)
	m.preview = previewState{}
	m.previewGen++
	return cmd
}

// freePreviewID returns the out-of-band delete for the current image id (nil if
// none allocated yet). Does not touch other preview state.
func (m *Model) freePreviewID() tea.Cmd {
	if m.preview.id == 0 {
		return nil
	}
	return tea.Raw(kittyDelete(m.preview.id))
}

// handlePreviewKey owns every keystroke while the modal is up. The configurable
// bindings drive it — the preview key (space by default) toggles it shut, and
// the list-left/right keys (←/h, →/l) cycle images — so a user's rebindings and
// vim_nav flow through. esc/q are the conventional modal dismiss (hardwired like
// the cheatsheet / open-picker modals); ctrl+c still quits.
func (m Model) handlePreviewKey(msg tea.KeyPressMsg) (tea.Model, tea.Cmd) {
	switch msg.String() {
	case "ctrl+c":
		return m, tea.Quit
	case "esc", "q":
		return m, m.closeImagePreview()
	}
	switch {
	case key.Matches(msg, m.keys.Preview): // same key that opened it closes it
		return m, m.closeImagePreview()
	case key.Matches(msg, m.keys.Right):
		return m.cyclePreview(1)
	case key.Matches(msg, m.keys.Left):
		return m.cyclePreview(-1)
	}
	return m, nil
}

// resizePreview re-fits the placement to the new terminal size and kicks off a
// background re-encode of every frame at that size. No-op unless a loaded
// preview is open. The placeholder grid follows the new cols/rows immediately;
// the re-fitted pixels arrive via previewReencodedMsg. Encoding stays off the UI
// goroutine, so even a large image doesn't stall a resize.
func (m *Model) resizePreview() tea.Cmd {
	if !m.preview.active || m.preview.id == 0 {
		return nil
	}
	if m.preview.streaming {
		return m.resizePreviewStream()
	}
	if len(m.preview.frames) == 0 {
		return nil
	}
	m.sizePreview()
	return m.reencodePreview(m.previewGen)
}

// reencodePreview returns a background command that re-builds the transmit
// sequence(s) at the current placement size (capturing everything now so a later
// cycle/close can't race the encode). Used by resizePreview.
//
// A native animation (m.preview.native) can't simply re-encode in place: its root
// frame already carries other frames appended to it at the old size, and
// re-transmitting a root under an id that already has animation frames is an
// interaction the protocol doesn't spell out (see previewState.id). So this instead
// allocates a fresh id up front — synchronously, like openPreviewItems/cyclePreview
// do — and builds the whole setup under it; handlePreviewReencoded swaps
// m.preview.id to it and frees the old one.
func (m *Model) reencodePreview(gen int) tea.Cmd {
	frames := m.preview.frames
	delays := m.preview.delays
	cols, rows := m.preview.cols, m.preview.rows
	cw, ch := m.cellPxW, m.cellPxH
	if m.preview.native {
		oldID := m.preview.id
		newID := m.emojiImg.allocID()
		mm := *m
		return func() tea.Msg {
			root, setup, err := mm.encodePreviewNative(frames, delays, cols, rows, newID)
			if err != nil {
				return previewReencodedMsg{gen: gen, err: err}
			}
			return previewReencodedMsg{gen: gen, seqs: []string{root}, nativeSetup: setup, id: newID, oldID: oldID}
		}
	}
	id := m.preview.id
	return func() tea.Msg {
		seqs, err := encodePreviewFrames(frames, cols, rows, id, cw, ch)
		if err != nil {
			return previewReencodedMsg{gen: gen, err: err}
		}
		return previewReencodedMsg{gen: gen, seqs: seqs}
	}
}

// previewMaxBox returns the largest cell box (cols × rows) the modal image may
// occupy, leaving room for the border, caption, hint, and a screen margin.
func (m *Model) previewMaxBox() (cols, rows int) {
	cols = m.width*9/10 - 4  // border (2) + padding (2)
	rows = m.height*9/10 - 6 // border (2) + caption + blank + hint + margin
	if cols < 4 {
		cols = 4
	}
	if rows < 2 {
		rows = 2
	}
	return cols, rows
}

// sizePreview sets preview.rows/cols from the image aspect and the terminal size.
func (m *Model) sizePreview() {
	if m.preview.img == nil {
		return
	}
	m.preview.cols, m.preview.rows = m.computePreviewCells(m.preview.img.Bounds())
}

// computePreviewCells is the pure form of sizePreview: the rows×cols placement
// for an image of bounds b at the current terminal size. Called off the main
// thread by loadPreviewImage so sizing, like encoding, doesn't touch the UI.
func (m Model) computePreviewCells(b image.Rectangle) (cols, rows int) {
	maxC, maxR := (&m).previewMaxBox()
	return fitImageCells(b.Dx(), b.Dy(), maxC, maxR, m.cellPxW, m.cellPxH)
}

// fitImageCells picks the rows×cols cell box for a wPx×hPx image within
// (maxCols, maxRows), preserving aspect. The Kitty protocol scales the image to
// fill the chosen box, so the box aspect is what keeps it undistorted.
//
// When the terminal reported its cell size (cellPxW, cellPxH both > 0) we work
// in real pixels. On HiDPI displays (e.g. Apple Silicon) the terminal reports
// physical pixels, so cellPxW ≈ 14 instead of 7. The scale cap is therefore
// floor(cellPxW/7), i.e. the device pixel ratio, so the image renders at its
// natural logical size (same cell count on 1x and 2x displays) rather than at
// half size. Without cell metrics we fall back to filling the box at an assumed
// ~1:2 cell aspect.
func fitImageCells(wPx, hPx, maxCols, maxRows, cellPxW, cellPxH int) (cols, rows int) {
	if wPx <= 0 || hPx <= 0 {
		return maxCols, maxRows
	}
	if cellPxW > 0 && cellPxH > 0 {
		// Cap scale at the estimated device pixel ratio so the image renders at
		// its natural logical size without upscaling beyond 1:1 logical pixels.
		dpr := math.Max(1.0, math.Floor(float64(cellPxW)/7.0))
		scale := math.Min(
			float64(maxCols*cellPxW)/float64(wPx),
			float64(maxRows*cellPxH)/float64(hPx),
		)
		if scale > dpr {
			scale = dpr
		}
		cols = int(math.Ceil(float64(wPx) * scale / float64(cellPxW)))
		rows = int(math.Ceil(float64(hPx) * scale / float64(cellPxH)))
	} else {
		// (cols·cellW)/(rows·cellH) = wPx/hPx, with cellH ≈ 2·cellW ⇒ cols/rows = 2·wPx/hPx.
		ratio := 2.0 * float64(wPx) / float64(hPx)
		cols = maxCols
		rows = int(math.Round(float64(cols) / ratio))
		if rows > maxRows {
			rows = maxRows
			cols = int(math.Round(float64(rows) * ratio))
		}
	}
	if cols < 1 {
		cols = 1
	}
	if rows < 1 {
		rows = 1
	}
	if cols > maxCols {
		cols = maxCols
	}
	if rows > maxRows {
		rows = maxRows
	}
	return cols, rows
}

// padImageForCells pads img with transparent pixels so it exactly fills the
// cols×rows cell area, eliminating any Kitty-side scaling. The target size in
// image-pixel space is cols*cellPxW/dpr × rows*cellPxH/dpr. If the target
// would be smaller than the image (downscale case, e.g. image bigger than modal)
// the original is returned unchanged and Kitty handles the scale; the ~1px
// rounding error is acceptable in that case. Also a no-op when cell dimensions
// are unknown (cellPxW/cellPxH == 0).
func padImageForCells(img image.Image, cols, rows, cellPxW, cellPxH int) image.Image {
	if cellPxW <= 0 || cellPxH <= 0 {
		return img
	}
	dpr := math.Max(1.0, math.Floor(float64(cellPxW)/7.0))
	targetW := int(math.Round(float64(cols*cellPxW) / dpr))
	targetH := int(math.Round(float64(rows*cellPxH) / dpr))
	b := img.Bounds()
	if targetW == b.Dx() && targetH == b.Dy() {
		return img
	}
	if targetW < b.Dx() || targetH < b.Dy() {
		return img // downscale case; Kitty scales, accept the tiny rounding error
	}
	out := image.NewNRGBA(image.Rect(0, 0, targetW, targetH))
	// out is zero-initialized (fully transparent); draw original at top-left.
	draw.Draw(out, b, img, b.Min, draw.Src)
	return out
}

// encodePreviewFrames right-sizes each frame to the rows×cols placement and
// builds its Kitty transmit sequence under id. Run off the main thread (the
// load/reencode commands) so a slow PNG encode never blocks the UI goroutine.
func encodePreviewFrames(frames []image.Image, cols, rows int, id uint32, cellPxW, cellPxH int) ([]string, error) {
	seqs := make([]string, len(frames))
	for i, f := range frames {
		fitted := fitFrameToCells(f, cols, rows, cellPxW, cellPxH)
		seq, err := kittyTransmitImage(id, fitted, rows, cols)
		if err != nil {
			return nil, fmt.Errorf("encode preview frame %d: %w", i, err)
		}
		seqs[i] = seq
	}
	return seqs, nil
}

// fitFrameToCells right-sizes a frame for a rows×cols Kitty placement so we
// neither PNG-encode nor transmit more pixels than the cells can display. The
// placement covers cols·cellPxW × rows·cellPxH physical pixels, so a larger
// frame is downscaled to that box (a quality filter) in-process. Previously the
// full frame was shipped and Kitty downscaled it — which meant encoding a
// multi-megapixel PNG (~1.8s) and streaming ~14 MB to the terminal for an
// ~800px box. A frame already within the box keeps the transparent-pad fit so
// Kitty doesn't upscale a small image. Cell metrics unknown → assume a typical
// 8×16 cell so a runaway image is still bounded.
func fitFrameToCells(frame image.Image, cols, rows, cellPxW, cellPxH int) image.Image {
	cw, ch := cellPxW, cellPxH
	if cw <= 0 || ch <= 0 {
		cw, ch = 8, 16
	}
	boxW, boxH := cols*cw, rows*ch
	b := frame.Bounds()
	if boxW <= 0 || boxH <= 0 || (b.Dx() <= boxW && b.Dy() <= boxH) {
		return padImageForCells(frame, cols, rows, cellPxW, cellPxH)
	}
	scale := math.Min(float64(boxW)/float64(b.Dx()), float64(boxH)/float64(b.Dy()))
	dstW := int(math.Round(float64(b.Dx()) * scale))
	dstH := int(math.Round(float64(b.Dy()) * scale))
	if dstW < 1 {
		dstW = 1
	}
	if dstH < 1 {
		dstH = 1
	}
	dst := image.NewRGBA(image.Rect(0, 0, dstW, dstH))
	xdraw.BiLinear.Scale(dst, dst.Bounds(), frame, b, xdraw.Src, nil)
	return dst
}

// previewImageBlock builds the placeholder grid (rows×cols cells pointing at the
// transmitted image id). Empty until the image is loaded and sized.
func (m *Model) previewImageBlock() string {
	if m.preview.img == nil || m.preview.id == 0 || m.preview.rows <= 0 || m.preview.cols <= 0 {
		return ""
	}
	return kittyPlaceholder(m.preview.id, m.preview.rows, m.preview.cols)
}

// renderPreviewPopup composes the bordered modal: the image (or a loading/error
// line), the caption, and a hint line. Centered by viewContent via lipgloss.Place.
func (m *Model) renderPreviewPopup() string {
	if !m.preview.active {
		return ""
	}
	maxC, _ := m.previewMaxBox()

	var body string
	switch {
	case m.preview.err != nil:
		body = lipgloss.NewStyle().Foreground(lipgloss.Color("9")).
			Render(truncate("couldn't load image: "+m.preview.err.Error(), maxC))
	case m.preview.loading || m.preview.img == nil:
		body = lipgloss.NewStyle().Foreground(dimColor).Render("loading image…")
	default:
		caption := lipgloss.NewStyle().Foreground(dimColor).
			Render(truncate(m.preview.caption, maxC))
		body = lipgloss.JoinVertical(lipgloss.Center, m.previewImageBlock(), caption)
	}

	hint := "space/esc/q close"
	if len(m.preview.items) > 1 {
		hint = fmt.Sprintf("%d/%d · ←/→ next · space/esc/q close",
			m.preview.idx+1, len(m.preview.items))
	}
	hintLine := lipgloss.NewStyle().Foreground(dimColor).Italic(true).Render(hint)

	content := lipgloss.JoinVertical(lipgloss.Center, body, "", hintLine)

	return lipgloss.NewStyle().
		Border(border).
		BorderForeground(focusedColor).
		Padding(0, 1).
		Render(content)
}
